#!/usr/bin/env zsh
if [[ -z $STOW_PKGS ]]; then
    STOW_PKGS="zsh,nvim,base"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

git submodule init && git submodule update
STOW_PKGS=$STOW_PKGS DOTFILES=$DOTFILES $DOTFILES/install
